
name: Delete Package Versions

description: Deletes package versions

inputs:

  keep-only:
    description: >
      Number of versions to keep.
      Defaults to 1.
    required: false
    default: "2"

  token:
    required: false
    default: ${{ github.token }}

runs:
  using: node12
  main: dist/index.js

branding:
  icon: package
  color: blue