name: Package and Smoke Test

on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:

  package: # make sure build/ci work properly
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Install
      run: yarn
  
    - name: Format
      run: yarn format-check
    
    - name: Build and Package
      run: yarn run pack

  smoke-test: # make sure the action works on a clean machine without building
    name: Smoke Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout Delete Package Versions Repo
    - uses: ./
      name: Smoke Test Delete Package Versions Action
      with:
        keep-only: 3